# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: serverKey
  inputs:
    secureFile: 'server.key'
  
- script: |
    npm install --global @salesforce/cli
    sf org login jwt --username deborahoxhaj@creative-shark-ijtyxy.com --jwt-key-file $(serverKey.secureFilePath) --client-id 3MVG9YFqzc_KnL.z9QfAg.GgqzmKyyc.YqPoFEK2s7PHy4wRgDJDjYH607qFqewXDxa.k8f1AhbdRXiWxynry --alias sandboxQA --set-default
    sf apex run test --synchronous
    sf project deploy start  --source-dir force-app --target-org sandboxQA --concise
  displayName: 'Run a multi-line script'
